### ISSUE TITLE
Download lineage/clade consensus mutations

### ISSUE THREAD

**Issue by MrOlm** [vector-engineering/covidcg#299]
Hello,

The website you've put together is pretty incredible and filled with useful information. Thank you for doing this and making the data so freely available.

I am particularly interested in exporting the "lineage x genomic coordinate" table (screenshot attached), but I am unable to do so. Whenever I click "download" I am only able to download the summary table of lineage counts by location, not the table of nucleotide coordinates. Accessing this table would be really useful for a wastewater monitoring program I am contributing to. 

Any way you can think of to access this data would be much appreciated, either officially through the website or in a hacky way by accessing the raw data bucket.

Thanks in advance,
Matt

![Screen Shot 2021-04-06 at 9 29 00 AM](https://user-images.githubusercontent.com/13424205/113929936-80215c00-97a5-11eb-8d11-207bb0a66cc5.png)

**Comment by atc3** [comment]
Hi Matt,

Thanks for the feedback.

Would it be more helpful to provide a table of all consensus mutations per lineage definition, in addition to the current download? For example:

```
lineage,mutations
B.1.1.7,N501Y;D614G;...
```

I can do this, or I can re-enable the download of the data displayed in the table. I'm not sure why I disabled it, but I can definitely add it back.

**Comment by MrOlm** [comment]
Hello,

Thanks for the quick feedback. The key piece of info that would be great to have are the nucleotide mutations for each lineage. Parsing the SARS-CoV-2 genome to translate the amino acid mutations to nucleotide mutations is difficult due to the ribosomal slip, and having a table of straight nucleotide mutations per lineage would be really useful for the application I'm working on.

Thanks,
Matt

**Comment by atc3** [comment]
Hi Matt,

Please find this file with consensus NT mutations for each pangolin lineage, as of today: [https://storage.googleapis.com/ve-public/lineage_dna_snp_20210408.csv](https://storage.googleapis.com/ve-public/lineage_dna_snp_20210408.csv). Let me know if this is what you're looking for.

I'll try to add this download to the main site in the next release.

**Comment by atc3** [comment]
*one more thing:

We define a "consensus" mutation as a mutation that occurs in 90% or more of the sequences in that lineage. Additionally, we are not the ones running the pangolin assignments (the assignments are provided to us from GISAID), although we plan to run them on our own in the future.

In the future we could provide mutation frequencies per lineage (i.e., percent sequences with this mutation) instead of just using this hard cutoff. Let me know if this would help

**Comment by MrOlm** [comment]
Hello,

Thank you for doing this- this is exactly what I was looking for. I used the table in some analyses I performed this morning and the results all looked great (expected lineages were present, unexpected lineages were not).

For now the table you've provided is working great- using GISAID / pangolin lineages is perfect, and the 90% cutoff seems to work great as well. Mutation frequencies per lineage could prove to be useful in the future (e.g. to know to which mutations are at 100% vs. 90%), as would be the ability to access a continually updated version of the above-linked table as new lineages emerge (e.g. as a download from the website).

Thanks again for doing this so quickly.
-Matt

**Comment by atc3** [comment]
In case this is still useful, I've added a download for consensus mutations. You can access it via. the download button in the sidebar:

![image](https://user-images.githubusercontent.com/3106207/117084819-31b89c00-ad16-11eb-8a33-ee16cf3febb6.png)

This opens a dialog with opens for NT/AA, as well as a threshold for excluding mutations that are not present in that fraction of sequences.

![image](https://user-images.githubusercontent.com/3106207/117084905-62003a80-ad16-11eb-9e0a-799141a5e2f6.png)

**Comment by rosekantor** [comment]
Hello,

Thank you so much for doing this!  I'm a colleague of Matt's, and I've been really appreciating your tool and the amount of time it saves me from having to parse the full GISAID alignment myself.  I see that 90% is still the hard cut-off for consensus mutations in the downloaded file, even though the dialogue box seems to let the user specify a different cut-off.  Do you have plans to add this feature? I am looking for a way to define signature mutations (e.g. present at frequency >90% in lineage of interest and <50% in all other lineages).  The download consensus tool gets me halfway there!  Also wanted to check if this table reflects all of GISAID or just the US and Canada as the site seems to imply.

Also, I don't know how hard this would be, but is it possible to include both nucleotide and amino acid mutations in the same table? The nucleotide variants are the most useful to me, but it would be nice not to have to translate them later on in my analysis.

Thanks again,
Rose

**Comment by atc3** [comment]
Hi Rose,

> I see that 90% is still the hard cut-off for consensus mutations in the downloaded file, even though the dialogue box seems to let the user specify a different cut-off. Do you have plans to add this feature?

I just tested the site and the endpoint and the user input for the mutation frequency threshold is working on my end. Can you let me know your specific query so that I can debug this error?

Alternatively, you can fetch the data programmatically:

```bash
$ curl --header "Content-Type: application/json" --request POST --data '{"group": "lineage", "snv_type": "gene_aa", "consensus_threshold": 0.9}' https://covidcg.org/group_snv_frequencies > out.json
```

Valid entries for `group` are `lineage` for Pango lineage and `clade` for the GISAID clade definition. Valid entries for `snv_type` are `dna` for NT SNVs, `gene_aa` for AA SNVs on the gene level, and `protein_aa` for AA SNVs on the protein level. `consensus_threshold` is the minimum frequency within a group for an SNV to be considered a "consensus SNV".

> I am looking for a way to define signature mutations (e.g. present at frequency >90% in lineage of interest and <50% in all other lineages).

If the mutation frequency threshold works correctly, you should be able to answer this by querying as many "consensus" mutations as possible my setting the threshold to something very low like 0.01, and then analyzing the resulting data.

> Also wanted to check if this table reflects all of GISAID or just the US and Canada as the site seems to imply.

The consensus mutation data is based off of all sequences (all data in GISAID, after QC filtering), not just the ones selected in the UI. 

> Also, I don't know how hard this would be, but is it possible to include both nucleotide and amino acid mutations in the same table? The nucleotide variants are the most useful to me, but it would be nice not to have to translate them later on in my analysis.

Sorry, we don't currently have data on what NT SNVs are synonymous/non-synonymous, and which AA SNVs they correspond to. This is definitely something worth having and I can look into extracting this data from our pipeline and storing it in our database.

Also as a side note – we are currently not processing any frameshifts (I know there is a prominent one in Orf7a). We're still working on getting frameshift mutations compatible with our system and will let you know when that is resolved, if the frameshifts are important for your work.

Hope this helps, and always happy to answer any additional questions.

Albert

**Comment by rosekantor** [comment]
Hi Albert,

I think I figured out where the bug is- if I download consensus mutations at 90%, save the file and then click the download button again without refreshing, the next file will always be the same as the previous file, regardless of whether I change the requested frequency.  If I refresh the page between downloads, everything works as expected.

One other thing I have noticed is that for insertions, frequencies are often reported well above 100%. This doesn't happen for any other mutations, which is good.

Thank you for answering all my other questions! I'm glad the data is based off of all of GISAID- definitely more useful this way.  I'd love to see both the NT and AA SNVs as separate columns in the download someday, but just having the NT table is a big help- it seems like every other site pulling from GISAID presents the data as AA SNVs.  I think frameshifts would probably be good to include in the future. 

For context, I am sequencing SARS-CoV-2 genomes from wastewater, which contains a mixture of lineages. I need to be able to tell public health folks what lineages *might* be there, so I have to compare the data to known SNVs and lineages in GISAID.

Rose
